### ISSUE TITLE
[Feature] Disable download progress bars

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmengine#755] opened 2022-11-22 20:16 UTC
### What is the feature?

Hi, when not using an interactive terminal (for example CloudWatch logs), each iteration of progress bars is printed to logs. So for example I typically have several hundred lines in my training logs that just print each iteration of progress bar for downloading checkpoint file(s). 

Is there already any way to disable progress bars for file downloads? If not, I'd like propose a feature for disabling this through a config option.

### Any other context?

For example (this goes on for several hundreds of lines):

> [1,mpirank:8,algo-2]<stderr>:#015  0%|          | 0.00/97.8M [00:00<?, ?B/s]
> [1,mpirank:15,algo-2]<stderr>:#015  0%|          | 0.00/97.8M [00:00<?, ?B/s]
> [1,mpirank:14,algo-2]<stderr>:#015  0%|          | 0.00/97.8M [00:00<?, ?B/s][1,mpirank:11,algo-2]<stderr>:#015  0%|          | 0.00/97.8M [00:00<?, ?B/s]
> [1,mpirank:12,algo-2]<stderr>:#015  0%|          | 0.00/97.8M [00:00<?, ?B/s]
> [1,mpirank:10,algo-2]<stderr>:#015  0%|          | 0.00/97.8M [00:00<?, ?B/s]
> [1,mpirank:13,algo-2]<stderr>:#015  0%|          | 0.00/97.8M [00:00<?, ?B/s]
> [1,mpirank:9,algo-2]<stderr>:#015  0%|          | 0.00/97.8M [00:00<?, ?B/s]
> [1,mpirank:15,algo-2]<stderr>:#015  5%|▍         | 4.70M/97.8M [00:00<00:02, 48.7MB/s]
> [1,mpirank:14,algo-2]<stderr>:#015  5%|▍         | 4.69M/97.8M [00:00<00:01, 49.1MB/s]
> [1,mpirank:11,algo-2]<stderr>:#015 11%|█         | 10.5M/97.8M [00:00<00:00, 110MB/s]
> [1,mpirank:10,algo-2]<stderr>:#015  8%|▊         | 7.95M/97.8M [00:00<00:01, 83.3MB/s]
> [1,mpirank:12,algo-2]<stderr>:#015  8%|▊         | 7.44M/97.8M [00:00<00:01, 77.1MB/s]
> [1,mpirank:8,algo-2]<stderr>:#015 11%|█▏        | 11.1M/97.8M [00:00<00:00, 106MB/s]
> [1,mpirank:13,algo-2]<stderr>:#015  8%|▊         | 7.66M/97.8M [00:00<00:01, 79.5MB/s]
> [1,mpirank:9,algo-2]<stderr>:#015  2%|▏         | 2.18M/97.8M [00:00<00:05, 19.4MB/s]
> [1,mpirank:10,algo-2]<stderr>:#015 17%|█▋        | 17.1M/97.8M [00:00<00:00, 90.5MB/s]
> [1,mpirank:15,algo-2]<stderr>:#015 14%|█▍        | 13.6M/97.8M [00:00<00:01, 72.6MB/s]
> [1,mpirank:14,algo-2]<stderr>:#015 12%|█▏        | 11.8M/97.8M [00:00<00:01, 61.7MB/s]
> [1,mpirank:8,algo-2]<stderr>:#015 22%|██▏       | 21.2M/97.8M [00:00<00:00, 106MB/s]

**Comment by zhouzaida** [comment] 2022-11-25 03:52
Hi @austinmw , thanks for your feedback. The progress bar is caused by `load_from_http` loading checkpoints from the Internet. We will find a proper way to support closing the progress bar.

**Comment by HAOCHENYE** [comment] 2022-11-25 06:01
@austinmw Hi! it seems the dirty progress bar is caused by https://github.com/open-mmlab/mmengine/blob/d3d75288351723105c933825c984dca2b4b64681/mmengine/utils/dl_utils/hub.py#L53 
`load_url` accepts the `progress` argument with the default value `True`, which causes the problem. Maybe we could set its default value according to whether it is in an interactive terminal or not?

**Comment by austinmw** [comment] 2022-11-25 15:48
Hi, thanks, that sounds like a great solution if possible. 

Not sure of the best way to do that, but this seems to correctly produce False in my environment:


```python
cmd = 'if [[ $- == *i* ]]; then echo "True"; else echo "False"; fi'
response = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
interactive = response.stdout.read().decode('utf-8').strip()
if interactive == 'True':
    progress = True
else:
    progress = False
```

**Comment by HAOCHENYE** [comment] 2022-11-25 16:15
Will this solution https://stackoverflow.com/questions/6108330/checking-for-interactive-shell-in-a-python-script be more elegant? I'm not sure if it will work for your environment.

**Comment by austinmw** [comment] 2022-11-25 19:18
Ah yes that solution works for me and is much cleaner!

**Comment by HAOCHENYE** [comment] 2022-11-26 08:38
> Ah yes that solution works in my environment (`os.isatty(0)` returns `False`) and is much cleaner!

Great :sunglasses::sunglasses: !, Would you mind proposing a PR to fix this this?

**Comment by austinmw** [comment] 2022-11-26 20:46
@HAOCHENYE Hey, let me know how https://github.com/open-mmlab/mmengine/pull/770/files looks. It works to remove the progress bars in my test environment.

**Closed** 2022-12-26 09:07 UTC
