### ISSUE TITLE
Does mmengine implement the early stopping?

### ISSUE THREAD

**Issue by RlChen0** [open-mmlab/mmengine#597] opened 2022-10-11 10:59 UTC
I saw mmengine support early stopping in the docs，but can’t find any instruction about it.

**Comment by zhouzaida** [comment] 2022-10-12 03:26
Hi @RlChen0 , mmengine does not support early stopping now but we have a plan to support it.

**Comment by MiXaiLL76** [comment] 2022-11-03 12:46
@zhouzaida any update?

Do you have plans to make your own implementation - or port someone else's?

If there is some kind of plan, but there are not enough hands, I think it is worth discussing and someone will take this job

**Comment by zhouzaida** [comment] 2022-12-20 08:00
Hi @MiXaiLL76 , #739 will support EarlyStoppingHook.

**Comment by zhouzaida** [comment] 2022-12-20 08:02
This issue is a duplicate of another issue, please discuss it under that issue #356.

**Closed by zhouzaida** 2022-12-20 08:02 UTC
Labels: planned feature
